### ISSUE TITLE
Landscape Message Center Alignment Problem

### ISSUE THREAD

**Issue by sgorbyo** [apptentive/apptentive-ios#148]
The problem appear on real device iPad 2 iOS 8.3(12F69) 64GB **NOT** on simulator.
I've captured the following from Apptentive Demo:

![img_0059](https://cloud.githubusercontent.com/assets/2874319/7340067/2ba9e6dc-ec85-11e4-8b67-c109fd9a8ccf.PNG)

And from my App:
![img_0056](https://cloud.githubusercontent.com/assets/2874319/7340148/f3f92f16-ec86-11e4-8c65-6b2ffbac670e.PNG)

**Comment by pkamb** [comment]
Hi @sgorbyo, thanks for reporting this.

We fixed the same or a similar issue in the recent 1.7.3 release. Would you be able to test to see if that fixed your issue?

Thanks!

https://github.com/apptentive/apptentive-ios/releases/tag/v1.7.3

**Comment by sgorbyo** [comment]
Hi pkamb, thank you very much for your answer.
It seems CocoaPods is still not aware of version 1.7.3 so I integrated apptentive using XCode.
Something changed for better but it is still not what we expect to see. Again it works in the simulator but this is how it appears on my iPad 2:

![img_0060](https://cloud.githubusercontent.com/assets/2874319/7438183/37294bd6-f060-11e4-8171-7b392ce922ea.PNG)

**Comment by pkamb** [comment]
Ah, thanks for the heads up about CocoaPods. 1.7.3 should now be available there as well.

Do you by chance have any other iPads to test this on in your app? Perhaps an original iPad Mini, or a newer Retina iPad? I'd be interested in hearing if it's just this iPad 2.

We will get our hands on some older hardware and test as well. Thanks!

**Comment by sgorbyo** [comment]
I'm sorry but I only have access to this hardware. I hope the problem could be limited to my iPad so, if you test with success on other (possibly similar) iPads please let me know.
Thank you.

**Comment by pkamb** [comment]
Same issue:
http://stackoverflow.com/questions/30237816/custom-uiwindow-on-ios-8-3-ipad-works-on-simulator-but-not-device

**Comment by sgorbyo** [comment]
Hi Peter,

Yes, it seems exactly the same weird behavior. Also in my case it started
since I migrated to Xcode 6.3.

I did a bit of tracing and I also discovered that the controller "feel" it
is in portrait instead of in landscape mode. Maybe a different way to
detect orientation in code or even a double check using two independent way
could help to understand the origin of the issue.

I don't have any idea of the number of devices affected, anyway even being
only an aesthetic issue, it happens exactly in the worst place, i.e. when
the user is giving his/her suggestion or asking for support.

Thank you and have a nice weekend,

Danilo

2015-05-30 1:24 GMT+02:00 Peter Kamb <notifications@github.com>:

**Comment by pkamb** [comment]
Thanks Danilo. I'm digging into this a bit and having a very hard time understanding what is going wrong.

The iOS bug seems to be isolated to iPad 2 hardware. iPad 2 Simulator is fine. iPad Mini is fine.

The OP on that StackOverflow post says:

 > We've discovered that setting the rootViewController on the UIWindow "solves" the problem.

Setting the window's `rootViewController` in our app isn't immediately successful by itself... the view/window hangs and isn't shown. After a delay it eventually crashes.

![screen shot 2015-05-29 at 5 27 31 pm](https://cloud.githubusercontent.com/assets/342355/7894882/36ff0abe-0628-11e5-8870-f9c495805b2b.png)

I will keep looking into this, and asked a few questions on the SO question.

The good news is that we are in the process of improving Message Center. We'll be moving away from this way of presenting the MC view, so this problem will be fixed.

Very sorry for the issue here! I'll let you know when I know more.

Peter

**Comment by pkamb** [comment]
The person who posted that Stack Overflow question updated it with an answer of setting the `rootViewController`, which fixed it in their app. Something like this may be possible, for anyone who finds this question. From my testing this simply forced our landscape iPad 2 into a portrait configuration, not really solving this iPad 2 bug and also introducing issues for other hardware.

```
blocker = [[UIWindow alloc] init];
[blocker setBackgroundColor:[UIColor colorWithRed:.0 green:.0 blue:.0 alpha:.8]];

UIViewController *blockerRoot = [UIViewController new];
blocker.rootViewController = blockerRoot;
CGRect r = [[UIScreen mainScreen] bounds];
[blocker setFrame:r];
```

Due to the complexities of the current Message Center presentation and rotation, the best way to go forward here is for us to 'fix' this in our next release of Message Center. We will be releasing a new version of Message Center soon that will offer many improvements and new features. We'll be sure to test the new version with the iPad 2 hardware to make sure this issue does not persist. Very sorry for the annoyance here, and look for that new version of Message Center soon. Thanks!
