### ISSUE TITLE
Crash in ApptentivePayloadSender deleteCompletedOrFailedRequest: 

### ISSUE THREAD

**Issue by matheda** [apptentive/apptentive-ios#197]
We are seeing a crash in our app that appears to be originating from the ApptentivePayloadSender deleteCompletedOrFailedRequest: method.  It is not in the stack trace for the crash itself, but in going through 20 instances of this crash (out of 275+), the only non-system code that is executing is this method.  See attached images for the stack traces.  Unfortunately Firebase doesn't give me a good way to paste the whole thing as text in any kind of easily readable format :-/

Not sure if this is helpful or not, but we have not seen this crash in versions of our app running version 3.x versions of the SDK, only the version that is running 4.0.2.

![screen shot 2017-08-16 at 9 51 49 am](https://user-images.githubusercontent.com/1895008/29367075-c4cdf4d0-8269-11e7-89fa-bfe31be5e37b.png)
![screen shot 2017-08-16 at 9 52 08 am](https://user-images.githubusercontent.com/1895008/29367077-c6f80020-8269-11e7-9b95-37b0e355b672.png)

**Comment by frankus** [comment]
I'm sorry that you're running into all of the teething problems with our new architecture (we've rearchitected the networking code, which is why this is present in 4.0.x but not 3.x). And thanks again for being forthcoming with your crash reports.

I've been looking at the code and don't yet see a smoking gun, but I'll continue to investigate and keep you updated with what I find.

**Comment by frankus** [comment]
As far as we can tell, the issue is due to a block sometimes being released while it's being executed, because the object that owns the block (in this case, a managed object context) is getting released. 

Any time the app exits, it would set up the preconditions for this to occur. I've push a fix to a branch (https://github.com/apptentive/apptentive-ios/tree/v4.0.4-pre) that you can try out. 

The fix makes the block capture the managed object context so that it can finish running before the managed object context (and hence the block) gets released. 

I've modified the code to have the block (indirectly) retain a reference to itself.

**Comment by matheda** [comment]
No problem, and we really appreciate how responsive you have been when we report an issue!  I just tried the updated SDK and did not have any issues.  I was not able to reproduce the crash before the fix, so I don't know if it has resolved the issue or not, but it seems stable in the small amount of testing I have done.

**Comment by matheda** [comment]
I wanted to follow up and see when this fix might be released.  We are continuing to see a large number of these crashes.  Thanks!

**Comment by matheda** [comment]
Also, I would like to clarify something you mentioned above...

> Any time the app exits, it would set up the preconditions for this to occur. 

By that do you mean the app going into the background?  We have received a number of reports of the app shutting down when backgrounded and I wanted to see if this was the cause.

**Comment by frankus** [comment]
Yes, that is what I mean.

**Comment by frankus** [comment]
We just released version 4.0.4 that should address this crash.

**Comment by matheda** [comment]
That's great news, thank you!

**Comment by matheda** [comment]
Unfortunately 4.0.4 didn't eliminate the issue.  We are still seeing this crash, although it has a slightly different stack trace now:

![screen shot 2017-09-03 at 6 43 23 am](https://user-images.githubusercontent.com/1895008/30002278-7e613fbc-9073-11e7-9a1e-70772542c17c.png)

**Comment by frankus** [comment]
I think this could be related to https://github.com/apptentive/apptentive-ios/issues/198. There is a significant bug in the way that we handle app exit in this part of the code. 

It would be manifested as the managed object context being released before it should and the background task completion handler not getting called, causing the system to kill the app. 

We will be releasing a patch in the near future and will update you when we do.

**Comment by frankus** [comment]
Version 4.0.5 (just released) fixes a problem with the background task that is used to save the Core Data stack on app exit. It is likely that a non-clean exit of the Core Data stack is to blame for this crash, so please update and let us know if it fixes the issue.

**Comment by matheda** [comment]
The latest version of our app was released on Friday and we did not see any of these crashes come in over the weekend.  This was our most frequently occurring crash so I would have expected to see it at least once if it were still an issue.  I think this can be closed, and I will write back in if it happens again.

**Comment by loevborg** [comment]
@frankus we have recently migrated from 3.x to 4.0.7, and unfortunately we are still seeing this issue, primarily on iOS 11 (11.0.2 and 11.0.3)

Here is the **Stacktrace**
`Crashed: NSManagedObjectContext 0x1c01c9600
0  libobjc.A.dylib                0x1841f8430 objc_msgSend + 16
1  Apptentive                     0x10314a744 __58-[ApptentivePayloadSender deleteCompletedOrFailedRequest:]_block_invoke + 32
2  CoreData                       0x18750eea4 developerSubmittedBlockToNSManagedObjectContextPerform + 156
3  libdispatch.dylib              0x184655048 _dispatch_client_callout + 16
4  libdispatch.dylib              0x184663580 _dispatch_sync_invoke_and_complete_recurse + 64
5  libdispatch.dylib              0x18466307c _dispatch_sync_wait + 516
6  CoreData                       0x18750eda8 -[NSManagedObjectContext performBlockAndWait:] + 304
7  Apptentive                     0x10314a6f4 -[ApptentivePayloadSender deleteCompletedOrFailedRequest:] + 144
8  Apptentive                     0x103149d8c -[ApptentivePayloadSender requestOperationDidFinish:] + 240
9  Apptentive                     0x10314e5a4 -[ApptentiveRequestOperationCallback requestOperationDidFinish:] + 108
10 Apptentive                     0x10314d3e8 -[ApptentiveRequestOperation processResponse:withObject:] + 496
11 Apptentive                     0x10314cee8 __39-[ApptentiveRequestOperation startTask]_block_invoke + 416
12 CFNetwork                      0x18525ad50 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 32
13 CFNetwork                      0x1852720ec __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 152
14 Foundation                     0x18569a310 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
15 Foundation                     0x1855da9e4 -[NSBlockOperation main] + 72
16 Foundation                     0x1855ca620 -[__NSOperationInternal _start:] + 848
17 libdispatch.dylib              0x184655048 _dispatch_client_callout + 16
18 libdispatch.dylib              0x18465c6c8 _dispatch_block_invoke_direct$VARIANT$mp + 288
19 libdispatch.dylib              0x184655048 _dispatch_client_callout + 16
20 libdispatch.dylib              0x18465c6c8 _dispatch_block_invoke_direct$VARIANT$mp + 288
21 libdispatch.dylib              0x18465c574 dispatch_block_perform$VARIANT$mp + 104
22 Foundation                     0x18569bfe8 __NSOQSchedule_f + 376
23 libdispatch.dylib              0x184655048 _dispatch_client_callout + 16
24 libdispatch.dylib              0x18465d3d4 _dispatch_continuation_pop$VARIANT$mp + 428
25 libdispatch.dylib              0x18465bcd4 _dispatch_async_redirect_invoke$VARIANT$mp + 604
26 libdispatch.dylib              0x1846621c8 _dispatch_root_queue_drain + 596
27 libdispatch.dylib              0x184661f10 _dispatch_worker_thread3 + 120
28 libsystem_pthread.dylib        0x1848fb130 _pthread_wqthread + 1268
29 libsystem_pthread.dylib        0x1848fac30 start_wqthread + 4`

**Comment by frankus** [comment]
@loevborg Thanks for the update. I will reopen the issue and we'll continue to try and track down a repro and fix.

**Comment by kubajakowski** [comment]
@frankus exact same issue in our app. Let me know if you need more info.

**Comment by frankus** [comment]
We finally tracked this down and have a fix included in the 4.1.1 release.

**Comment by vgupta20** [comment]
@frankus The earlier version I had was 4.0.7 to get this issue fixed I updated my pod and got an updated version 4.1.0

How will I get 4.1.1?

**Comment by frankus** [comment]
I wonder if this might be a problem with CocoaPods. Their website is showing 4.1.1 as the current version: https://cocoapods.org/pods/apptentive-ios.
